first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^showform/', views.showform, name='showform'),
    url(r'^newtopic/', views.newtopic, name='newtopic'),
    url(r'^register/', views.register, name='register'),
    url(r'^user_login/', views.user_login, name='user_login')
]

music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index, name="index"),
]

website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/', views.logout, name='logout'),

]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.PROTECT)

    portfolio_site = models.URLField(blank=True)
    profile_pics = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.PROTECT)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

music/models.py
from django.db import models

# Create your models here.

first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import Topic, UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pics')

'''
Creating a model form
'''


class NewTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = "__all__"


"""
This function is for creating ur custom validators that will be used by the validators
Django class. It has to be created outside the class and must be have a value params
"""


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError('Name must start with a z')


class TopicForm(forms.Form):
    name = forms.CharField(max_length=200, validators=[check_for_z])
    email = forms.EmailField()
    verifyemail = forms.EmailField(label='Verify Email')
    message = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=True, widget=forms.HiddenInput,
                                 validators = [validators.MaxLengthValidator(0)]
                                 )

    """
        This is the way a validation function is created. 
        the syntax is clean_fieldElementName
    """
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("THAT FIELD IS HIDDEN AND NOT MEANT TO BE FILLED.")
    #     return botcatcher

    '''
        This is used to clean all the forms at once 
    '''
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verifyemail']

        if email != vmail:
            raise forms.ValidationError('Emails do not match')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import AccessRecord, Topic, Webpage
from . import forms
from first_app.forms import NewTopicForm, UserProfileInfoForm, UserForm
from django.contrib.auth.forms import User


# Imports for login
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    access_records = AccessRecord.objects.order_by('date')
    data = {"access_records": access_records}
    return render(request, 'first_app/index.html', data)


def user_login(request):

    # Check if the user posted login info

    if request.method == 'POST':

        username = request.POST.get("username")
        password = request.POST.get("password")

        # Authenticate the user
        user = authenticate(username=username, password=password)

        # If the user was authenticated
        if user:
            if user.is_active:
                login(request, user)
                # Redirect the user if they are logged in
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account In active")
        else:
            print("Somee tired to login and failed")
            return HttpResponse("Invalid user login details")
    else:
        return render(request, 'first_app/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('/index/'))


def register(request):

    registered = False

    if request.method == 'POST':
        # Grab the data from the POST
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check if the form is valid and save the user data
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            # Hash the user password
            user.set_password(user.password)
            # Save the latest data
            user.save()

            # commit the profile information without saving them: This is because we havent
            # checked if the user provided an image(profile pics)
            profile = profile_form.save(commit=False)
            # Set the user id. this is used to fulfile the OneToOneField
            # Registered on our Form.py file
            profile.user = user

            if 'profile_pics' in request.FILES:
                profile.profile_pics = request.FILES['profile_pics']

                profile.save()

                registered = True

            else:
                print(user_form.errors, profile_form.errors)
    else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html',
                      {"profile_form": profile_form, 'user_form': user_form, 'registered': registered})


def showform(request):

    if request.method == 'POST':
        topicForm = forms.TopicForm(request.POST)
        if topicForm.is_valid():
            data = {
                'TopicForm': topicForm,
                "status": "success",
                "form_data_name": topicForm.cleaned_data['name'],
                "form_data_email": topicForm.cleaned_data['email'],
                "form_data_message": topicForm.cleaned_data['message'],
            }
        else:
            print('Invalid form')
            data = {'TopicForm': topicForm}
        return render(request, 'first_app/my_form.html', data)
    else:
        topicForm = forms.TopicForm()
        data = {'TopicForm': topicForm}
        return render(request, 'first_app/my_form.html', data)


def newtopic(request):

    new_topic_form = NewTopicForm()
    topics = Topic.objects.order_by('top_name')

    if request.method == 'POST':
        new_topic_form = NewTopicForm(request.POST)

        if new_topic_form.is_valid():
            new_topic_form.save(commit=True)
            return render(request, "first_app/topics.html", {'form': new_topic_form, 'topics':topics})
        else:
            print("Invalid form")

    return render(request, "first_app/topics.html", {'form': new_topic_form, 'topics':topics})

music/views.py
from django.shortcuts import render

# Create your views here.

templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First App</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'index' %}">Home</a></li>
      <li><a href="{% url 'first_app:showform' %}"> Show Form</a></li>
        <li><a href="{% url 'first_app:newtopic' %}"> New topic</a></li>
        <li><a href="{% url 'admin:index' %}"> Admin Page</a></li>

        {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}"> Logout</a></li>
        {% else %}
            <li><a href="{% url 'first_app:user_login' %}"> Login</a></li>
        {% endif %}

    </ul>
  </div>
</nav>

{% block main_content %}

{% endblock %}
</body>
</html>

templates/first_app/index.html
{% extends 'first_app/base.html' %}

{% block main_content %}


    <h1>Access Records</h1>

    {% if access_records %}

        <table>
            <thead>
            <tr>
                <td>Site Name</td>
                <td>Site URL</td>
            </tr>
            </thead>
            <tbody>

            {% for access_record in access_records %}
            <tr>
                <td>{{ access_record.name|cut:'Ltd' }}</td>
                <td>{{ access_record.date }}</td>
            </tr>

            {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>No access record found</p>

    {% endif %}
{% endblock %}

templates/first_app/login.html
 {% extends 'first_app/base.html' %}

{% block main_content %}
    <div class="container">
        <form action="{% url 'first_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="Username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="Password">Password:</label>
            <input type="password" name="password">

            <input type="submit" value="Submit">

        </form>

    </div>

{% endblock %}

templates/first_app/my_form.html
 {% extends 'first_app/base.html' %}

{% block main_content %}
    <div class="container">
        <h3>Complete the form below</h3>
        <form method="post">
            {{ TopicForm.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit" />
        </form>

       {%  if  status  %}:
           <h2>Form Response;</h2>
            <p>Name: {{ form_data_name}}</p>
            <p>Email: {{ form_data_email}}</p>
            <p>Message: {{ form_data_message }}</p>
       {% endif %}
    </div>

{% endblock %}

templates/first_app/registration.html
 {% extends 'first_app/base.html' %}

{% block main_content %}
    <div class="container">
        {% if registered %}
            <h3>Thank you for registering</h3>
        {% else %}
            <h3>Registration</h3>
            <form method="POST" enctype="multipart/form-data">

                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                {% csrf_token %}
            <input type="submit">
            </form>
        {% endif %}

    </div>

{% endblock %}

templates/first_app/topics.html
{% extends 'first_app/base.html' %}

{% block main_content %}

 <form method="post">
{{ form }}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Save Post" />
</form>

{% for topic in topics %}
    <p>{{ topic.top_name }}</p>
{% endfor %}


{% endblock %}